-- ⑮ 다들 뭐 골랐을까 — 문항 은행 시드
-- 이 파일은 scripts/gen-majority-questions.mjs 가 생성합니다. 직접 수정하지 마세요.
-- 문항을 추가·수정할 때는 스크립트를 고치고 `node scripts/gen-majority-questions.mjs` 를 다시 실행하세요.
--
-- 수량: food 16 / cafe 7 / cvs 6 / travel 9 / daily 22 / season 6 / taste 8 = 총 74문항
-- 표(snap/live)는 0 에서 시작합니다. 표본이 모이기 전까지 그 문항은 "집계 중" 으로
-- 판정 없이 통과 처리되고 점수도 0 입니다 (없는 비율을 지어내지 않습니다).

INSERT INTO majority_questions (topic, prompt, option_a, option_b, active, created_at) VALUES
  ('food', '치킨은 역시?', '후라이드', '양념', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '라면에 넣는 계란은?', '풀어서', '통째로', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '오늘 중국집에서는?', '짜장면', '짬뽕', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '탕수육 소스는?', '부먹', '찍먹', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '피자 테두리는?', '남긴다', '먹는다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '떡볶이에 곁들인다면?', '튀김', '순대', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '삼겹살은 어디에 찍어?', '소금', '쌈장', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '회는 어디에 찍어?', '초장', '간장', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '계란후라이는?', '완숙', '반숙', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '여름 냉면은?', '물냉면', '비빔냉면', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '라면 국물이 남으면?', '밥 말기', '그냥 버리기', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '붕어빵은 어디부터?', '머리부터', '꼬리부터', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '만두는?', '군만두', '물만두', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '치킨에 곁들일 음료는?', '콜라', '맥주', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '김밥 먹을 때 함께?', '라면', '어묵국', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('food', '햄버거 세트 사이드는?', '감자튀김', '치즈스틱', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '오늘 커피는?', '아이스', '따뜻하게', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '카페 자리는?', '창가', '구석', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '한 잔 고른다면?', '아메리카노', '라떼', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '케이크 한 조각은?', '초코', '치즈', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '여름 빙수는?', '팥빙수', '과일빙수', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '텀블러는?', '챙긴다', '안 챙긴다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cafe', '디저트는 언제?', '커피와 함께', '다 마시고', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '여름 편의점 간식 하나만?', '아이스크림', '아이스 커피', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '편의점에서 한 끼는?', '도시락', '삼각김밥', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '신상 과자를 보면?', '일단 사본다', '먹던 걸 산다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '컵라면은?', '뜨거울 때 바로', '조금 식혀서', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '편의점 커피는?', '원두 커피', '캔커피', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('cvs', '계산할 때 봉투는?', '받는다', '안 받는다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '이번 휴가는?', '바다', '산', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '여행 계획은?', '꼼꼼하게', '즉흥적으로', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '짧은 해외여행지는?', '오사카', '다낭', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '여행 짐은?', '캐리어', '배낭', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '숙소는?', '호텔', '게스트하우스', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '비행기 좌석은?', '창가', '복도', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '국내 여행이라면?', '제주', '강릉', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '여행지에서 아침은?', '늦잠', '일찍 출발', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('travel', '기념품은?', '많이 산다', '거의 안 산다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '아침 알람이 울리면?', '한 번에 일어난다', '5분만 더', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '지하철에서는?', '영상', '음악', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '주말 계획은?', '집에서 쉬기', '밖에 나가기', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '설거지는?', '먹고 바로', '나중에 한 번에', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '새 앱을 받으면?', '설명을 읽는다', '바로 눌러본다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '영화관 좌석은?', '앞쪽', '뒤쪽', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '드라마는?', '몰아보기', '한 편씩', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '메시지 답장은?', '바로', '생각하고', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '장보기는?', '온라인', '직접 가서', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '2층까지 간다면?', '계단', '엘리베이터', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '이어폰 설정은?', '노이즈캔슬링', '주변 소리', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '사진 찍을 때는?', '정면', '살짝 옆으로', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '우산은?', '항상 챙긴다', '비 올 때만', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '배터리가 20% 남으면?', '바로 충전', '끝까지 쓴다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '휴대폰 알림은?', '거의 켜둔다', '거의 끈다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '이불 정리는?', '매일 한다', '가끔 한다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '밥 먹을 때 화면은?', '켜둔다', '끈다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '새로 산 옷은?', '바로 입는다', '아껴둔다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '약속 장소에는?', '미리 도착', '시간 맞춰', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '청소는?', '주말에 몰아서', '매일 조금씩', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '영수증은?', '받는다', '안 받는다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('daily', '엘리베이터 닫힘 버튼은?', '누른다', '기다린다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '여름 실내 온도는?', '24도', '26도', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '겨울 이불은?', '두꺼운 것 하나', '얇은 것 여러 장', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '봄에 하고 싶은 건?', '피크닉', '벚꽃 구경', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '첫눈이 오면?', '사진을 찍는다', '그냥 본다', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '장마철 신발은?', '장화', '그냥 운동화', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('season', '겨울 외투는?', '긴 패딩', '짧은 패딩', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '노래방 첫 곡은?', '발라드', '신나는 곡', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '게임은?', '혼자', '같이', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '책은?', '종이책', '전자책', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '듣는 음악은?', '최신곡', '듣던 노래', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '둘 중 하나라면?', '강아지', '고양이', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '나는 어느 쪽?', '아침형', '저녁형', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '보너스가 생기면?', '저축', '여행', 1, CAST(strftime('%s','now') AS INTEGER) * 1000),
  ('taste', '운동은?', '아침', '저녁', 1, CAST(strftime('%s','now') AS INTEGER) * 1000);
